version: '3'
services:
  webserver:
    image: 'nginx:alpine'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './:/var/www'
      - './.docker/nginx/conf.d:/etc/nginx/conf.d/'
    networks:
      - docker-php
    depends_on:
      - app
      - db
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - './:/var/www'
    working_dir: '/var/www'
    networks:
      - docker-php
  db:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/database'
    networks:
      - docker-php
networks:
  docker-php:
    driver: bridge
volumes:
  mysql:
    driver: local